config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root 'static_pages#index', as: 'root'

  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/about'

  resources :transactions
  resources :accounts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:account_id, :destination_account_id,
                                          :amount, :destination_account_amount, :comment, :category_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.select :account_id, account_names_and_ids, {}, { 'class':'form-control' } %>
  </div>

  <div class="field">
    <%= form.label :destination_account_id %>
    <%= form.select :destination_account_id, account_names_and_ids, {}, { 'class':'form-control' } %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, { :class => 'form-control' } %>
  </div>

  <div class="field">
    <%= form.label :destination_account_amount %>
    <%= form.text_field :destination_account_amount, { :class => 'form-control' } %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, { :class => 'form-control' } %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id, { :class => 'form-control' } %>
  </div>

  <div class="actions">
    <%= form.submit({ :class => 'btn btn-warning'}) %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Account_id</th>
      <th>Destination_account_id</th>
      <th>Amount</th>
      <th>Destination_account_amount</th>
      <th>Comment</th>
      <th>Category_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.account_id %></td>
        <td><%= transaction.destination_account_id %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.destination_account_amount %></td>
        <td><%= transaction.comment %></td>
        <td><%= transaction.category_id %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account_id: </strong>
  <%= @transaction.account_id %>
</p>

<p>
  <strong>Destination_account_id: </strong>
  <%= @transaction.destination_account_id %>
</p>

<p>
  <strong>Amount: </strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Destination_account_amount: </strong>
  <%= @transaction.destination_account_amount %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @transaction.comment %>
</p>

<p>
  <strong>Category_id: </strong>
  <%= @transaction.category_id %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>