config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root 'static_pages#index', as: 'root'

  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/about'

  resources :transactions
  resources :accounts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div>
  <br>
  <hr>
  <br>
  <div class="container footer">
    <br>
    <strong>HomeFinance@2019</strong>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <nav>
    <menu>
      <menuitem id="demo1">
        <a>New</a>
        <menu>
          <menuitem>
            <!-- Button trigger modal -->
            <a data-toggle="modal" data-target="#accountModal">Account</a>
          </menuitem>
          <menuitem>
            <a>Transaction</a>
            <menu>
              <menuitem>
                <!-- Button trigger modal -->
                <a data-toggle="modal" data-target="#incomeModal">Income</a>
              </menuitem>
              <menuitem>
                <!-- Button trigger modal -->
                <a data-toggle="modal" data-target="#expanseModal">Expanse</a>
              </menuitem>
              <menuitem>
                <!-- Button trigger modal -->
                <a data-toggle="modal" data-target="#transferModal">Transfer</a>
              </menuitem>
            </menu>
          </menuitem>
        </menu>
      </menuitem>

      <menuitem>
        <a>Categories</a>
        <menu>
          <menuitem>
            <!-- Button trigger modal -->
            <a data-toggle="modal" data-target="#categoryModal">New</a>
          </menuitem>
          <menuitem>
            <!-- Button trigger modal -->
            <a data-toggle="modal" data-target="#view-categoryModal">View</a>
          </menuitem>
        </menu>
      </menuitem>

      <menuitem><%= link_to 'Home', static_pages_home_url %></menuitem>
      <menuitem><%= link_to 'About', static_pages_about_url %></menuitem>

    </menu>
    <br>
    <hr>
    <br>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeFinance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <div id="app">
        <%= yield %>
      </div>

      <%= render 'layouts/footer' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
      <%= javascript_pack_tag 'application' %>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    </div>
  </body>
<% if user_signed_in? %>
  <%= link_to 'Profile', current_user %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

<%= yield %>
</body>
</html>