config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root 'static_pages#index', as: 'root'

  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/about'

  resources :transactions
  resources :accounts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord

  enum currency: { :UAH => 'UAH', :USD => 'USD', :EUR =>'EUR', :RUR => 'RUR' },
       color: { 'Red': 'lightcoral', 'Blue': 'lightskyblue', 'Green': 'lightgreen',
                'Yellow': 'yellow', 'Pink': 'lightpink', 'Orange': 'orange',
                'Grey': 'lightgrey' }

  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: 1..18
  validates :currency, presence: true
  # validates :user_id, presence: true

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        init_transaction(Account.last.id, Account.last.title)
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:title, :currency, :color, :user_id)
    end

    def init_transaction(id, title)
      transaction = Transaction.new('account_id': id, 'amount': '0',
                      'comment': "Счёт #{title} создан")
      transaction.save
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>

  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, { :class => 'form-control' }%>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.select :currency, Account.currencies.keys, {}, { :class => 'form-control' }%>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, { :class => 'form-control' }%>
  </div>

  <div class="actions">
    <%= form.submit({ :class => 'btn btn-warning'}) %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Currency</th>
      <th>User_Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.title %></td>
        <td><%= account.currency %></td>
        <td><%= account.user_id %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @account.title %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @account.currency %>
</p>

<p>
  <strong>User_id:</strong>
  <%= @account.user_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>